export const SEND_MESSAGE = 'SEND_MESSAGE'
export const CONNECTED_NEW_USER = 'CONNECTED_NEW_USER'
export const DISCONNECTED_USER = 'DISCONNECTED_USER'
export const RECEIVE_NEW_MESSAGE = 'RECEIVE_NEW_MESSAGE'
